# Generated by Django 3.2.7 on 2021-09-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('requestdate', models.CharField(max_length=500)),
                ('requestdeadline', models.IntegerField()),
                ('apikeys', models.CharField(max_length=5000)),
                ('expiring', models.IntegerField()),
                ('expired', models.IntegerField()),
            ],
        ),
    ]
