# Generated by Django 3.2.7 on 2021-09-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='apikeysstring',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
